# Versió del format de docker-compose utilitzat.
# La 3.8 és compatible amb les funcionalitats de Docker actuals.
version: '3.8'

# Plugins: instal·lar pluguins de Visual Studio Code per a Docker i YAML
# Docker DX Docker (De Microsoft) i YAML (De Red Hat) per a una millor experiència de desenvolupament.
# Entre d'alte coses, permet executar comandes de Docker directament des del codi i validar la sintaxi YAML.

services:
  # 1. Servei de Base de Dades (MariaDB)
  # Equivalent a docker run -d --rm --name c_bd3 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db_dawe -e MYSQL_USER=user_dawe -e MYSQL_PASSWORD=pwd mariadb:10.6
  c_bd3:
    image: mariadb:10.6  
    container_name: c_bd3
    # Nota: El --rm no es posa aquí, el Compose gestiona el cicle de vida amb 'down'
    environment: # Variables d'entorn per configurar la base de dades en el primer inici.      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_dawe
      MYSQL_USER: user_dawe
      MYSQL_PASSWORD: pwd
    restart: always  # Reinicia el contenidor al fallar o després d'un reboot de l'host

  # 2. Servei de PHPMyAdmin (Gestor web)
  # equivalent a docker run -d --rm --name c_phpmyadmin3 -p 8080:80 -e PMA_HOST=c_bd3 -e MYSQL_ROOT_PASSWORD=root phpmyadmin:latest
  c_phpmyadmin3:
    image: phpmyadmin:latest 
    container_name: c_phpmyadmin3 # equivalent a --name c_phpmyadmin3
    ports:
      - "8080:80"   # Mapeig de port: -p 8080:80
    environment: # Variables d'entorn per configurar la connexió a la base de dades
      PMA_HOST: c_bd3
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - c_bd3       # Espera que la BD estigui llista